#!/usr/bin/env bash
# configure the SSH config file to our needs so that
# you can connect to a server without typing a password

Host 54.209.118.131
  IdentityFile ~/.ssh/school
  PasswordAuthentication no
  
